openSUSE/microos-tools

selinux/98selinux-microos/selinux-microos-relabel.sh
This fixes that umount -R /sysroot/sys tried to umount inside the real /sys.
=> selinux-microos-relabel.sh: Don't propagate umounts into the real root

selinux/98selinux-microos/selinux-microos-relabel.sh
See the added comment for the rationale.
This doesn't do anything on its own, but tries to make sure that it doesn't destroy `/var/lib/overlay` (also breaking other snapshots) by accident.
=> Make sure /var/lib/overlay exists before relabeling

devel-tools/sysext-add-debug
Small tool to "install" debug rpms as overlay using systemd-sysext.
=> Add sysext-add-debug

selinux/98selinux-microos/selinux-microos-relabel.sh
security=selinux or even builtin kernel defaults are enough to enable selinux,
so checking for selinux=1 specifically is not enough.
=> 98selinux-microos: Don't rely on selinux=1 (bsc#1202449)

selinux/98selinux-microos/module-setup.sh, selinux/98selinux-microos/selinux-microos-relabel.sh
Previously this relied on a kernel bug: It was possible to change xattrs of
files on read-only subvolumes.
=> 98selinux-microos: Make the btrfs subvolume writable temporarily (boo#1202395)

selinux/98selinux-microos/module-setup.sh
`chroot` is not unconditionally installed in the initrd since https://github.com/dracutdevs/dracut/commit/51813371
This fix is needed for dracut-059, issue found in https://build.opensuse.org/request/show/1046083
```
Jan 03 11:07:26 localhost dracut-pre-pivot[511]: SELinux: relabeling root filesystem
Jan 03 11:07:26 localhost dracut-pre-pivot[511]: SELinux: loading policy
Jan 03 11:07:26 localhost dracut-pre-pivot[511]: //lib/dracut/hooks/pre-pivot/50-selinux-microos-relabel.sh: line 44: chroot: command not found
```
=> 98selinux-microos: Add chroot as dependency

selinux/98selinux-microos/selinux-microos-relabel.sh
```
```
Also make sure the .relabelled flag file itself is also labelled correctly.
=> 98selinux-microos: Work around overlayfs bug (bsc#1210690)

systemd-proxy-env/setup-systemd-proxy-env
- Lowercase `l` in `rm -f $TMPCFGFIlE`
- `DefaultEnvironment=""` variable ended up being `DefaultEnvironent`
- `SOCKS5_SERVER` case adds `SOCKS5_PROXY` to default environment
=> systemd-proxy-env: fix typos in setup-systemd-proxy-env

selinux/98selinux-microos/module-setup.sh, selinux/98selinux-microos/selinux-microos-relabel.sh
One of the commits converts tabs to spaces, so to get a proper diff look at the commits individually.
~Draft because not tested yet.~ Works!
=> 98selinux-microos: Set mount propagation properly + other small fixes

selinux/98selinux-microos/selinux-microos-relabel.sh
https://github.com/util-linux/util-linux/issues/2551 got fixed, so the additional umount is no longer necessary with newer versions. Make it conditional.
Draft because I need to test it first.
=> 98selinux-microos: Avoid "/sysroot-selinux: not mounted" on new util-linux

selinux/98selinux-microos/selinux-microos-relabel.sh
If the initgrub parameter is set, the initrd's job is to run GRUB and jump to the real kernel + initrd with kexec.
=> Don't run in the zipl initrd "initgrub" mode

selinux/98selinux-microos/selinux-microos-relabel.sh, selinux/selinux-autorelabel-generator
restorecon has the -T option to set how many cores are used for setting labels
The default is 1
Setting -T 0 uses all cores, which makes perfect sense considering we're blocking the boot while restoring here - those cores aren't going to be doing anything else
On an old Dell XPS13 this results in the following kind of speedup
2476k files with default single threaded operation - 2m23.455s
same fileset with -T 0 (4 core CPU) - 1m3.572s
That's quite a speedbost IMO
=> Use all cores for SELinux restorecon

.obs/workflows.yml
Branching within a project creates links which accumulate. Use trigger_services instead.
=> Fix OBS workflow for pushes to master

microos-tools.spec
ATM it's only triggered for the main package, which works on Micro, but on TW this will be used standalone
=> Regenerate initrd after selinux-autorelabel installation

selinux/selinux-autorelabel-generator
Otherwise they'll never be considered active and local-fs.target will never be fully reached. Anything triggering multiple starts of local-fs.target would start the -relabel services again, eventually failing due to start-limit-hit.
=> Add RemainAfterExit=true to autorelabel services

test/test.sh, test/testscript
=> test: Check for AVC denials in the journal

selinux/selinux-autorelabel-generator
Skip remote and automount filesystems and those without support for labelling.
=> Only autorelabel local filesystems with SELinux support (boo#1237202)

test/testscript
While sshd.service starts, the labels inside are not fully consistent with the policy, leading to false positives like:
[   13.887904] combustion-validate[1602]: Would relabel /etc/ssh/ssh_host_rsa_key.XXXXzVExEt from system_u:object_r:sshd_key_t:s0 to system_u:object_r:etc_t:s0
=> test: Wait for sshd.service before checking labels in /etc

test/testscript
cant reproduce, neither locally nor on github
see https://bugzilla.suse.com/show_bug.cgi?id=1231012
=> Drop wtmpdb SELinux AVC workaround in test suite

man-online
If we have only one argument and the manual page starts with a number (2ping, 8tunnel), man-online interprets this as section.
=> Only parse section with at minimum two arguments (#42)

selinux/selinux-autorelabel-generator
It checked / instead of the actual mount entry.
=> selinux-autorelabel: Fix check for relabelling only specific filesystems

man-online
If the product is "SLES", fetch the manual pages from "Leap-$version" to have manual pages which fits best instead of using newest manual pages from Tumbleweed.
=> man-online: fetch product specific manual pages

selinux/98selinux-microos/module-setup.sh
This fixes cases where /var needs other devices to become available. Need to call an internal dracut function to make this simple...
~Draft because this needs more testing.~
=> 98selinux-microos: Also include parent devices needed for /var

Makefile.am, configure.ac, zypp-single-rpmtrans/10-zypp-single-rpmtrans.conf, zypp-single-rpmtrans/Makefile.am, zypp-single-rpmtrans/zypp-single-rpmtrans.sh
Set ZYPP_SINGLE_RPMTRANS=1 on commandline and for systemd servcies, so that libzypp will use single rpmtrans where ever called.
=> Use single rpmtrans with libzypp by default
